apiVersion: devops.kubesphere.io/v1alpha1
kind: Releaser
metadata:
  creationTimestamp: null
  name: linuxsuren-bot-test-3
spec:
  gitOps:
    enable: true
    repository:
      address: https://github.com/linuxsuren-bot/ks-release-mgr
      branch: master
      name: test
  phase: ready
  repositories:
  - action: pre-release
    address: https://github.com/linuxsuren-bot/test
    branch: master
    name: linuxsuren-bot-test
  secret:
    name: linuxsuren-bot
    namespace: ks-releaser-system
  version: v0.0.8
status: {}
